In Out model
swd-bits-goa/swd_django pull request #325
Opened 2021-08-31 15:32 UTC by Aviral09

A tab to make entry of students coming in or going out.
A tab to view all students currently out of campus.
Login with credentials for security.

2021-08-31 18:52 UTC, khizirsiddiqui requested changes
Additionally there are several unused import, please remove them.

2021-08-31 18:52 UTC, khizirsiddiqui commented on swd/gate_security/urls.py
> +url(r'^in_out/', views.in_out, name='in_out'),
Put this url under /gate_security only. Just to ensure uniformity.

2021-08-31 18:52 UTC, khizirsiddiqui commented on swd/gate_security/views.py
> +                }
Should show error in case of failure. Ex- Invalid Student ID or Unapproved Leave or whatever the reason maybe.

2021-08-31 18:52 UTC, khizirsiddiqui commented on swd/main/admin.py
> +from gate_security.models import *
Move this to gate_security App

2021-08-31 18:52 UTC, khizirsiddiqui commented on swd/main/schema/types.py
> +from gate_security.models import *
You can remove this, we have stopped using graphene.

2021-08-31 18:52 UTC, khizirsiddiqui commented on swd/gate_security/views.py
> +        inout = InOut.objects.filter(student__bitsId=username)
Use `objects.get` instead of `filter` to get a single object, faster and also, you can use try-except block to check for errors.

2021-08-31 18:52 UTC, khizirsiddiqui commented on swd/gate_security/models.py
> +from main.models import *
Unused Import?

2021-08-31 20:45 UTC, Aviral09 commented on swd/gate_security/views.py
> +                }
I am considering showing the button to activate leave and day pass only in case of approved leaves and daypasses so this shouldn't happen.

2021-09-01 05:30 UTC, khizirsiddiqui commented on swd/gate_security/views.py
> +                }
The present logic will check for any leave in history rather than the present applicable leave. You can put another condition on timestamp.
Wrong BITS ID error should also be shown, in case BarCode reader reads barcode wrong.

2021-09-01 05:31 UTC, khizirsiddiqui commented on swd/main/schema/types.py
> +#         model = InOut
remove instead of commenting : )

2021-09-01 07:48 UTC, ashadhaz commented
Also migrate `dash_security_leaves` and `dash_security_daypass` from main to gate_security.

2021-09-01 07:48 UTC, ashadhaz commented on swd/gate_security/admin.py
> +    search_fields = ['student__name']
Please add BitsID to this as well

2021-09-01 07:48 UTC, ashadhaz commented on swd/gate_security/views.py
> +    context = {
context should be just:

context = {
  'inout': inout
}

2021-09-01 07:48 UTC, ashadhaz commented on swd/gate_security/views.py
> +    inout = InOut.Objects.filter(inCampus = False)
O of Objects should be smallcase

2021-09-04 08:51 UTC, Aviral09 commented on swd/gate_security/views.py
> +from datetime import date, datetime, timedelta
Yes I have done that, will commit with the next batch of changes

2021-09-04 08:53 UTC, Aviral09 commented on swd/gate_security/views.py
> +                if '1' in 'activate1':
Once the guard enters the BITSID and Place the student is going to, the code automatically records the time etc. Now, if the student has an active leave and/or a daypass, it displays two buttons on the screen 'Activate leave' 'activate daypass' on which guard can click to activate the same. If none of these are there, only an input entry of the student is made in the system. No further action reqd.

2021-09-04 08:53 UTC, Aviral09 commented on swd/gate_security/views.py
> +                if '2' in 'activate2':
Explained above.

2021-09-08 13:16 UTC, khizirsiddiqui approved these changes

2021-09-18 04:24 UTC, khizirsiddiqui commented on swd/templates/swd.html
> +			<td>21</td>
Fetch count from database instead of hard-coding here.

2021-09-18 04:30 UTC, khizirsiddiqui commented on swd/main/views.py
> +            return redirect('/gate_security/security_leaves')
Use `redirect(view_name)` instead of `redirect(url)`.
See: [https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#redirect](https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#redirect)

2021-09-18 04:30 UTC, khizirsiddiqui commented on swd/main/views.py
> +            return redirect('/gate_security/security_leaves')
Use `redirect(view_name)` instead of `redirect(url)`.
See: [https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#redirect](https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#redirect)

2021-09-18 04:30 UTC, khizirsiddiqui commented on swd/main/views.py
> +                return redirect('/gate_security/security_leaves')
Use `redirect(view_name)` instead of `redirect(url)`.
See: [https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#redirect](https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#redirect)

2021-09-18 04:30 UTC, khizirsiddiqui commented on swd/gate_security/views.py
> +    return render(request, "gate_security.html", {'header': "Enter students coming in or going out of campus"},context)
signature of function is: `render(request, template_name, context=None, content_type=None, status=None, using=None)`
Please fix if this is unintentional.

2021-09-18 04:35 UTC, Aviral09 commented on swd/templates/swd.html
> +			<td>21</td>
Shall I add another hostel in the HOSTEL tuple in models.py as well? What is the hostel name to be added?

2021-09-18 04:48 UTC, khizirsiddiqui commented on swd/templates/swd.html
> +			<td>21</td>
Just fetch the count from database for now, we will add more hostels in `main/models.py` after discussion.

2021-09-18 04:54 UTC, Aviral09 commented on swd/templates/swd.html
> +			<td>21</td>
Cool

2021-11-10 09:21 UTC, merged