Minor refactoring of populate_data.py, also creates fake notices
swd-bits-goa/swd_django pull request #355
Opened 2022-04-05 22:30 UTC by robo-mop

Modified populate_data.py to show the progress of each population
Also creates 15 fake notices to test the default pagination (10 per page)

Modified notice.html to keep the endfor tag after the closing p tag (keeping if before doesn't match the opening order of tags)

2022-04-06 09:13 UTC, khizirsiddiqui reviewed
Good start mate.

2022-04-06 09:13 UTC, khizirsiddiqui commented on swd/populate_data.py
> +                hostel=", ".join(hostel_choices[4*i : 4*i+4]), # Convenient solution because the number of hostels is divisible by 4
For now the number of hostels are divisible by four, can you instead make it safe from this assumption for future?

2022-04-06 09:13 UTC, khizirsiddiqui commented on swd/populate_data.py
>      parser.add_argument('--id_start', type=int, default=20180001,
Since you are working on this, can you add args to specify number of entries to populate and use it as well.

2022-04-06 09:13 UTC, khizirsiddiqui commented on swd/populate_data.py
>      if student_success:
Can you add `else` condition as well? It will be convinient to know when something is not populated.

2022-04-06 09:13 UTC, khizirsiddiqui commented on swd/templates/notice.html
> +          {% endfor %}
Try to keep different PRs for different purposes.

Good start nonetheless.

2022-04-06 09:14 UTC, khizirsiddiqui commented on swd/templates/notice.html
> +          {% endfor %}
You can ignore this for now.

2022-04-06 09:16 UTC, Aviral09 requested changes

2022-04-06 09:16 UTC, Aviral09 commented on swd/populate_data.py
> +                hostel=", ".join(hostel_choices[4*i : 4*i+4]), # Convenient solution because the number of hostels is divisible by 4
Stick to a general case, right now they are divisible by 4, in future they may not be.

2022-04-06 09:49 UTC, ashadhaz-nutanix65 commented
Great start @robo-mop ! If we could also have degrees for HD and PhD in branch choices and assign degree based on username (eg if ID starts with 'p' it'll assign a PhD degree, similar for HD) that would be a great addition! 

Currently all the `branch_choices` contain just FD degrees. You can get a list of degrees from @Aviral09 for HD and PhD degree codes.

2022-04-06 10:03 UTC, robo-mop commented on swd/populate_data.py
>      parser.add_argument('--id_start', type=int, default=20180001,
Sure, no problemo

2022-04-06 10:34 UTC, khizirsiddiqui commented on swd/populate_data.py
>      parser.add_argument('--id_start', type=int, default=20180001,
Datasets categorization based on size seems a good way to organize it.

2022-04-08 22:40 UTC, robo-mop commented on swd/populate_data.py
> +    return f"{year}{branch}{uid}G"
I think you accidentally read the f inside of the quotations? XD
It's just an `f string` to replace the verbose `year + branch + uid + "G"`

2022-04-08 22:40 UTC, robo-mop commented on swd/populate_data.py
> +    return f"{year}{branch}PS{uid}G"
Sure thing

2022-04-08 22:43 UTC, robo-mop commented on swd/populate_data.py
> +    create_securities(number=10)
Yep it is. The naming conventions could be improved further, but I just followed the practices already set, since I didn't wanna change too much in one commit.

2022-04-09 06:55 UTC, ashadhaz commented on swd/populate_data.py
> +    return f"{year}{branch}{uid}G"
Ah! Yes my bad 😁

2022-04-09 06:56 UTC, ashadhaz commented on swd/populate_data.py
> +    create_securities(number=10)
Great, so currently we just have one login for the main gate security. Any specific reason why you're creating 10? If not we can just create 1.

2022-04-10 09:21 UTC, robo-mop commented on swd/populate_data.py
> +    create_securities(number=10)
Ah yeah, good point. I assumed there'd be one separate security user per pc or something, but keeping only 1 does make sense.

2022-06-12 12:32 UTC, merged